repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
    - id: mypy
      additional_dependencies: []

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      stages: [manual]  # example duplicate avoided; keep the first ruff hook

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements

- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.0
  hooks:
    - id: pyupgrade
      args: ["--py39-plus"]

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
    - id: codespell
      args: ["-L", "nd"]

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
    - id: detect-secrets
      args: ["--baseline", ".secrets.baseline"]
